# This workflow will build the static files
# and upload them to the given s3 bucket
name: Deploy to staging

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  build_and_deploy:
    name: Deploy

    environment:
      name: staging
      url: "https://staging-auth.avantifellows.org"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install
        run: npm install

      - name: Build
        env:
          NODE_ENV: staging
          VITE_APP_PLIO_AF_API_KEY: ${{ secrets.VITE_APP_PLIO_AF_API_KEY }}
          VITE_APP_BASE_URL_AF_PLIO: "https://app.plio.in/#/af/play/"
          VITE_APP_BASE_URL_SCERT_PLIO: "https://app.plio.in/scertH/play/"
          VITE_APP_PLIO_SCERT_API_KEY: ${{ secrets.VITE_APP_PLIO_SCERT_API_KEY }}
          VITE_APP_QUIZ_AF_API_KEY: ${{ secrets.VITE_APP_QUIZ_AF_API_KEY }}
          VITE_APP_BASE_URL_QUIZ: "https://staging-quiz.avantifellows.org/quiz/"
          VITE_APP_BASE_URL_FORM: "https://staging-quiz.avantifellows.org/form/"
          VITE_APP_BASE_URL_MEET: "https://meet.google.com/"
          VITE_APP_OTP_SERVICE: ${{ secrets.VITE_APP_OTP_SERVICE }}
          VITE_APP_BASE_URL_YOUTUBE: "https://www.youtube.com/watch?v="
          VITE_APP_PORTAL_BACKEND: "https://b93ddkdz0g.execute-api.ap-south-1.amazonaws.com/"
          VITE_APP_STUDENT_QUIZ_REPORT_BASE_URL: "https://reports-staging.avantifellows.org/reports/student_quiz_report/v3"
          VITE_APP_FORM_REPORT_BASE_URL: "https://reports-staging.avantifellows.org/reports/form_respones"
          VITE_APP_GURUKUL_BASE_URL: "https://staging-gurukul.avantifellows.org/"
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist s3://af-auth-layer-staging --delete --acl public-read
